### PR TITLE
Add additional fields to Cargo.toml

### PR DESCRIPTION
**Pull request by protheory8**

### CODE REVIEW

**Review by dyc3 — CHANGES_REQUESTED** [review]
Cargo.lock shouldn't be modified

**Comment by protheory8** [comment]
Why not? I get that it's not the purpose of this PR, but making a PR just to update lock file kinda feels lame.

**Comment by dyc3** [comment]
> I get that it's not the purpose of this PR

That's precisely why. Don't update `Cargo.lock` because it doesn't need to be updated.

**Comment by protheory8** [comment]
IIRC `license` field accepts SPDX license expressions, so it's either `GPL-3.0-only` or `GPL-3.0-or-later`. It's unclear under which one of these the project licensed under, so I chose the former one.

**Review by dyc3 — APPROVED** [review]

**Pull request merged**
