### PR TITLE
Check formatting in CI

### PR DESCRIPTION
**Pull request by protheory8**
Didn't test.

### CODE REVIEW

**Comment by protheory8** [comment]
I didn't find `fn_args_layout` option in the page I sent, not sure what that is.

**Comment by protheory8** [comment]
We want to make sure that changes compile with stable Rust, so I'll change a few things.

**Comment by protheory8** [comment]
Seems like the check is passing now.

**Comment by dyc3** [comment]
Well, it looks like it works

**Comment by protheory8** [comment]
How am I supposed to format code if I don't have nightly toolchain installed?

**Comment by dyc3** [comment]
Install the nightly toolchain, and use `cargo +nightly fmt` to format the code. Updating the readme...

**Comment by protheory8** [comment]
The problem is that I don't want to install nightly in the first place haha.

**Comment by dyc3** [comment]
Yeah but I don't think that there's a way around it. For everything else in this project, you shouldn't use the nightly toolchain. You don't have to set nightly as your default toolchain.

**Pull request merged**
